_BASE_: "../Base-bagtricks.yml"

DATASETS:
  NAMES: ("Hazy_Market1501",)
  TESTS: ("DukeMTMC", "Hazy_DukeMTMC")

TDATASETS:
  NAMES: ("Hazy_DukeMTMC",)

SOLVER:
  D_BASE_LR: (0.0001)
  D_OPT: ("Adam") # SGD

# ISM
MODEL:
  WEIGHTS: "/home/pj/fast-reid-master/logs/hazy-market1501/bagtricks_R50/baseline/model_final.pth"
  LOSSES:
    NAME:  ['s_CrossEntropyLoss',  'Dis_loss', 'BachDistance_loss_t',]

  PARAM:
    KD_PARAM: (0.1)
    KD_TEMP: (10.)
    KD_red: ("mean")
    BD_param: (4.)
    METRIC: ("euclidean") # "cosine, euclidean"
    Dis_mode: "mix"
    Dis_iter: 0.99
    BASEMODE: False
    Dis_net: "cam_Classifier"

OUTPUT_DIR: "/home/pj/fast-reid-master/logs/hazy-market1501/bagtricks_R50"
