_BASE_: "Base-Strongerbaseline.yml"

MODEL:
  META_ARCHITECTURE: 'MGN'

  FREEZE_LAYERS: ["backbone", "b1", "b2", "b3",]

  BACKBONE:
    WITH_NL: False

  HEADS:
    IN_FEAT: 256

  LOSSES:
    NAME: ("CrossEntropyLoss", "TripletLoss",)
    CE:
      EPSILON: 0.1
      SCALE: 0.125

    TRI:
      MARGIN: 0.0
      HARD_MINING: True
      NORM_FEAT: False
      SCALE: 0.20

